name: Release Fix

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Version of the release to fix"
        required: true

jobs:
  release_fix:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ github.event.inputs.release_version }}
      FIX_RUN_NUMBER: ${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all branches

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout release branch
        run: git checkout releases/${{ env.RELEASE_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.14"

      - name: Install dependencies
        run: npm ci

      - name: Type checking and tests
        run: |
          npm run type-check &
          npm test &
          wait

      - name: Build Docker image
        run: |
          docker build -t cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ env.RELEASE_VERSION }}_fix${{ env.FIX_RUN_NUMBER }} .
          docker tag cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ env.RELEASE_VERSION }}_fix${{ env.FIX_RUN_NUMBER }} cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ env.RELEASE_VERSION }}_latest

      - name: Login to Yandex Container Registry
        env:
          YANDEX_OAUTH_TOKEN: ${{ secrets.YANDEX_OAUTH_TOKEN }}
        run: |
          echo $YANDEX_OAUTH_TOKEN | docker login --username oauth --password-stdin cr.yandex

      - name: Push Docker image
        run: |
          docker push cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ env.RELEASE_VERSION }}_fix${{ env.FIX_RUN_NUMBER }}
          docker push cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ env.RELEASE_VERSION }}_latest

      - name: Tag release fix
        run: |
          git tag ${ env.RELEASE_VERSION }_fix${ env.FIX_RUN_NUMBER }
          git push origin ${ env.RELEASE_VERSION }_fix${ env.FIX_RUN_NUMBER }

      - name: Get previous tag
        id: prev_tag
        run: echo "::set-output name=prev_tag::$(git describe --tags --abbrev=0 HEAD^)"

      - name: Get commit list
        id: commits
        run: echo "::set-output name=commits::$(git log --pretty=format:'%h - %s' ${{ steps.prev_tag.outputs.prev_tag }}..HEAD)"

      - name: Add comment to GitHub Issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ secrets.ISSUE_NUMBER }}
          body: |
            ## Fix for Release ${{ env.RELEASE_VERSION }}
            **Date:** $(date)
            **Author:** ${{ github.actor }}
            **Commits:**
            ${{ steps.commits.outputs.commits }}
            **Docker Image:** cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ env.RELEASE_VERSION }}_fix${{ env.FIX_RUN_NUMBER }}
